name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x' # Версия Node.js

      - name: Install dependencies
        run: npm install

      - name: Prettier the project
        run: npm run prettier # Corrected to use npm run

      - name: Lint the project
        run: npm run lint # Corrected to use npm run

      - name: Build and Deploy the project
        run: npm run deploy # This will build the project and deploy to gh-pages
